import { ExtendedCardProps } from "@/components/card/types";

export const testcards: ExtendedCardProps[] = [
  {
    id: "player-1",
    kind: "card",
    player: "1",
    captain: true,
    dribble: 1,
    energy: 1,
    size: "sm",
    defense: 7,
    color: "yellow",
    hover: false,
  },
  {
    id: "player-2",
    kind: "card",
    player: "1",
    captain: true,
    dribble: 1,
    energy: 1,
    size: "sm",
    defense: 7,
    color: "yellow",
    hover: false,
  },
  {
    id: "player-3",
    kind: "card",
    player: "1",
    captain: true,
    dribble: 1,
    energy: 1,
    size: "sm",
    defense: 7,
    color: "yellow",
    hover: false,
  },
  {
    id: "player-4",
    kind: "card",
    player: "1",
    captain: true,
    dribble: 1,
    energy: 1,
    size: "sm",
    defense: 7,
    color: "yellow",
    hover: false,
  },
];
